### ISSUE TITLE
Error in train conformer

### ISSUE THREAD

**Issue by fra1993** [k2-fsa/icefall#102]
Following the instructions for training the conformer ctc model, I get the following error:

`transformer.py", line 706, in forward
    x = x * self.xscale + self.pe[:, : x.size(1), :]
IndexError: too many indices for tensor of dimension 2
`

I am currently running the simples command:
 `./conformer_ctc/train.py --world-size 1`

Any idea of what the problem could be?

**Comment by csukuangfj** [comment]
The same error as the one mentioned in
https://github.com/k2-fsa/icefall/issues/70#issuecomment-943205832

which has been fixed 19 days ago in  https://github.com/k2-fsa/icefall/pull/79

Are you using the latest master branch?

**Comment by fra1993** [comment]
I have tried to do a fresh installation of k2, lhotse and icefall but I noticed the following errors:

1. If you install lhotse via pip, you get installed torch 1.9 which dosn't work with current k2 version (this does not happen if you install via git)
2. after installing icefall, when I try the data preparation pipeline (./prepare.sh) I get `ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`

**Comment by csukuangfj** [comment]
> If you install lhotse via pip, you get installed torch 1.9 which dosn't work with current k2 version

How did you install k2? I guess you are encountering the issue which should have been fixed by https://github.com/lhotse-speech/lhotse/pull/466
If you install torchaudio before installing lhotse, then everything should be fine.

---

> ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

I also don't have this `.so` in my installation (Note I am using `pip`).  Perhaps you are using `conda` to install `k2`?

**Comment by fra1993** [comment]
Yes I use conda to install k2. Should I use pip?

**Comment by csukuangfj** [comment]
> Yes I use conda to install k2. Should I use pip?

No, conda is fine. I think the problem is that
- You installed k2 using conda, which also installed k2's dependency PyTorch
- Then you installed lhotse using `pip`, which installed `torchaudio`, which **re-installed** PyTorch

So the problem is that `torchaudio` installed by `lhotse` automatically replaced your already installed PyTorch with a newer version.

I would suggest the following workaround:

(1) Pass `torchaudio` to `conda install` when you install `k2` with conda
(2) Then reinstall the latest lhotse.

---

Another workaround is to install a version of k2 that is compiled against torch 1.9

**Comment by pzelasko** [comment]
Try to install everything again but in a clean environment. Latest Lhotse release won’t break your PyTorch installation anymore.

**Comment by fra1993** [comment]
After new installation I still have the original error. The output of `k2.version` is the following:

`k2 version: 1.10
Build type: Release
Git SHA1: e6db5dcc0017d2788cbf5d57b7967d9f46c73601
Git date: Tue Nov 2 13:23:57 2021
Cuda used to build k2: 11.1
cuDNN used to build k2: 8.0.4
Python version used to build k2: 3.8
OS used to build k2: Ubuntu 18.04.6 LTS
CMake version: 3.18.4
GCC version: 7.5.0
CMAKE_CUDA_FLAGS:  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 --expt-extended-lambda -gencode arch=compute_80,code=sm_80 --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall --compiler-options -Wno-unknown-pragmas --compiler-options -Wno-strict-overflow
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-strict-overflow
PyTorch version used to build k2: 1.8.1
PyTorch is using Cuda: 11.1
NVTX enabled: True
With CUDA: True
Disable debug: True
Sync kernels : False
Disable checks: False
`
The output of `python3 -m torch.utils.collect_env` is:

`PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.0a0+e4e171a
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_9    conda-forge
[conda] k2                        1.10.dev20211103 cuda11.1_py3.8_torch1.8.1    k2-fsa
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h497a2fe_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.21.2           py38h20f2e39_0
[conda] numpy-base                1.21.2           py38h79a1101_0
[conda] pytorch                   1.8.1           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.1                      py38    pytorch
`

**Comment by csukuangfj** [comment]
Can you check that you are using the latest master?

**Comment by fra1993** [comment]
I have installed icefall in the clean environment I used 
`git clone https://github.com/k2-fsa/icefall
cd icefall
pip install -r requirements.txt`
that should be the latest master branch, isn't it?

**Comment by csukuangfj** [comment]
> that should be the latest master branch, isn't it?


Could you show us the detailed error log?
At the start of the training, it prints some log about your environment, i.g, git-sha1 of k2, icefall, lhotse.

---

From
> transformer.py", line 706, in forward x = x * self.xscale + self.pe[:, : x.size(1), :] IndexError: too many indices for tensor of dimension 2

At line 706, it is a comment line in the latest master, see below:
https://github.com/k2-fsa/icefall/blob/b9452235d521fa717f2adef87a25585c3b644843/egs/librispeech/ASR/conformer_ctc/transformer.py#L706-L710

**Comment by fra1993** [comment]
This is the complete error I get
`2021-11-14 10:48:35,056 INFO [train.py:541] Training started
2021-11-14 10:48:35,056 INFO [train.py:542] {'exp_dir': PosixPath('conformer_ctc/exp'), 'lang_dir': PosixPath('data/lang_bpe'), 'best_train_loss': inf,
'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 10, 'reset_interval': 200,
'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'use_feat_batchnorm': True, 'attention_dim': 512, 'nhead': 8, 'num_decoder_layers': 6,
 'beam_size': 10, 'reduction': 'sum', 'use_double_scores': True, 'att_rate': 0.7, 'weight_decay': 1e-06, 'lr_factor': 5.0, 'warm_step': 80000,
 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 35, 'start_epoch': 0, 'full_libri': True, 'feature_dir': PosixPath('data/fbank'),
 'max_duration': 200.0, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0,
 'on_the_fly_feats': False, 'shuffle': True, 'return_cuts': True, 'num_workers': 2}
2021-11-14 10:48:35,291 INFO [lexicon.py:113] Loading pre-compiled data/lang_bpe/Linv.pt
2021-11-14 10:48:35,747 INFO [train.py:564] About to create model
2021-11-14 10:48:56,666 INFO [asr_datamodule.py:158] About to get train cuts
2021-11-14 10:48:56,667 INFO [asr_datamodule.py:322] About to get train cuts
2021-11-14 10:49:46,965 INFO [asr_datamodule.py:161] About to get Musan cuts
2021-11-14 10:49:47,888 INFO [asr_datamodule.py:164] About to create train dataset
2021-11-14 10:49:47,889 INFO [asr_datamodule.py:216] Using BucketingSampler.
2021-11-14 10:49:51,710 INFO [asr_datamodule.py:232] About to create train dataloader
2021-11-14 10:49:51,711 INFO [asr_datamodule.py:245] About to get dev cuts
2021-11-14 10:49:51,711 INFO [asr_datamodule.py:340] About to get dev cuts
2021-11-14 10:49:51,972 INFO [asr_datamodule.py:256] About to create dev dataset
2021-11-14 10:49:51,980 INFO [asr_datamodule.py:275] About to create dev dataloader
2021-11-14 10:49:51,980 INFO [train.py:608] epoch 0, learning rate 0
Traceback (most recent call last):
  File "./conformer_ctc/train.py", line 654, in <module>
    main()
  File "./conformer_ctc/train.py", line 647, in main
    run(rank=0, world_size=1, args=args)
  File "./conformer_ctc/train.py", line 612, in run
    train_one_epoch(
  File "./conformer_ctc/train.py", line 463, in train_one_epoch
    loss, loss_info = compute_loss(
  File "./conformer_ctc/train.py", line 362, in compute_loss
    att_loss = model.decoder_forward(
  File "/fs/scratch/users/francesco_nespoli/ASR/k2_experiments/icefall/egs/librispeech/ASR/conformer_ctc/transformer.py", line 293, in decoder_forward
    tgt = self.decoder_pos(tgt)
  File "/usr/local/envs/k2_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/ASR/k2_experiments/icefall/egs/librispeech/ASR/conformer_ctc/transformer.py", line 706, in forward
    x = x * self.xscale + self.pe[:, : x.size(1), :]
IndexError: too many indices for tensor of dimension 2
`

**Comment by csukuangfj** [comment]
No, the error log shows that you.are.not.using the latest master.

You are using 

/fs/scratch/users/francesco_nespoli/ASR/k2_experiments/icefall/egs/librispeech/ASR/conformer_ctc/transformer.py

Please make sure

/fs/scratch/users/francesco_nespoli/ASR/k2_experiments/icefall

is the one that you cloned a moment ago.

**Comment by csukuangfj** [comment]
Please refer to
https://icefall.readthedocs.io/en/latest/installation/index.html#download-icefall
for how to install `icefall`

**Comment by fra1993** [comment]
Hi, sorry if I didn't get back to you sooner. The problem was solved and it was on my side (I had more versions of icefall). How long should it take to train the conformer (single gpu training is the only option available right?) in my case it is taking more than 10 days...

**Comment by csukuangfj** [comment]
>  How long should it take to train the conformer (single gpu training is the only option available right?)

No, it does support single-node multiple-GPU training. All you need to do is to use `--world-size N` when running `./conformer_ctc/train.py`. (Please see https://icefall.readthedocs.io/en/latest/recipes/librispeech/conformer_ctc.html#training for more information).

---

>  in my case it is taking more than 10 days

If you use 3 GPUs, each epoch takes about 3 hours 45 minutes and if you use 4 GPUs, the time for each epoch is about 2 hours 30 minutes. Note that the training data is speed perturbed by factors 0.9 and 1.1 so there are actually `960 x 3` hours of training data.

---

> How long should it take to train the conformer

You will get a WER of 2.7 on test-clean after 17 epochs. If you train it for more epochs, the WER will continue to decrease.
