### ISSUE TITLE
Noise augmentation on audio level (supervision {s.id} has a mismatched recording_id)

### ISSUE THREAD

**Issue by mohsen-goodarzi** [k2-fsa/icefall#319]
Hi,
I am using a DNN-based feature extraction method in `conformer_ctc`. As it does not make sense to augment noise on feature level here, I decided to mix noise on audio level before feature extraction in `compute_fbank_librispeech.py` (of course it is not fbank any more) as follows:
```
            if "train" in partition:
                cut_set = (
                    cut_set
                    + cut_set.perturb_speed(0.9)
                    + cut_set.perturb_speed(1.1)
                )
                musan_cuts = (
                    CutSet.from_manifests(
                        recordings=combine(
                        part["recordings"] for part in musan_manifests.values()
                        )
                    )
                    .cut_into_windows(10.0)
                    .filter(lambda c: c.duration > 5)
                )
                cut_set = cut_set.mix(cuts=musan_cuts, mix_prob=0.5, snr=(10, 20), preserve_id="left")
            cut_set = cut_set.compute_and_store_features(...

```
But at the beginning of training I get the following error:
```
    f"MonoCut {c.id}: supervision {s.id} has a mismatched recording_id "
AssertionError: MonoCut da17d335-5a9c-4849-9442-38e526a7f7e8: supervision 6272-70171-0007_sp0.9 has a mismatched recording_id (expected None, supervision has 6272-70171-0007_sp0.9)
```

Why there is id mismatched while I set `preserve_id="left"`? Am I doing it right?

**Comment by csukuangfj** [comment]
Maybe @pzelasko  can comment.

**Comment by pzelasko** [comment]
Interesting. The `preserve_id` option shouldn't matter here. Can you paste the output of `print(cut)` for the problematic example? It looks like your cut has `recording_id=None` for some reason, which is not supposed to happen.

**Comment by pzelasko** [comment]
Also please paste the full call stack, I'm not sure where you got that exception.

**Comment by pzelasko** [comment]
OK I think I figured it out -- some assertions in `validate_cut` were only correct for MonoCut, but not for MixedCut. I fixed this in PR https://github.com/lhotse-speech/lhotse/pull/677, feel free to check out if it helps you.

**Comment by mohsen-goodarzi** [comment]
Thank you for fast solution.
To test the solution, as I am working in a docker container,  I had to rebuild the docker image to install new Lhotse.
But now I get the following error while calling train.py:
```
Traceback (most recent call last):
  File "./wav2vec2_conformer_ctc/train.py", line 26, in <module>
    import k2
  File "/opt/conda/lib/python3.7/site-packages/k2-1.14.dev20220418+cuda10.2.torch1.9.0-py3.7-linux-x86_64.egg/k2/__init__.py", line 2, in <module>
    from .torch_version import k2_torch_cuda_version
ModuleNotFoundError: No module named 'k2.torch_version'
```
My Dockerfile contains the following lines to install k2, Lhotse, and icefall (dependencies installations are not shown here):
```
#install k2 from source
RUN git clone https://github.com/k2-fsa/k2.git /opt/k2 && \
    cd /opt/k2 && \
    python3 setup.py install && \
    cd -

# install  lhotse
RUN pip install torchaudio==0.9.0 && \
    pip install git+https://github.com/lhotse-speech/lhotse

# install icefall
RUN git clone https://github.com/k2-fsa/icefall && \
    cd icefall && \
    pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

```

**Comment by pzelasko** [comment]
@csukuangfj can help you with k2. One thing I noticed though is that you're installing torchaudio separately from pytorch, this may lead to errors later. You'd best install them both in a single pip/conda command.

**Comment by csukuangfj** [comment]
@mohsen-goodarzi 
Please pull the latest k2. It was just fixed in https://github.com/k2-fsa/k2/pull/958

**Comment by csukuangfj** [comment]
Also, I would recommend you to first install `pytorch` and `torch`, and then install `k2` and `lhotse`.

```dockerfile
RUN pip install torch==1.9.0 torchaudio==0.9.0 && \
  \
  pip install git+https://github.com/lhotse-speech/lhotse && \
  \
  git clone https://github.com/k2-fsa/k2.git /opt/k2 && \
  cd /opt/k2 && \
  python3 setup.py install && \
  cd - && \
  \
  git clone https://github.com/k2-fsa/icefall && \
  cd icefall && \
  pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && \
  cd - && \
  \
  rm ~/.cache/pip
```

**Comment by mohsen-goodarzi** [comment]
> Also, I would recommend you to first install `pytorch` and `torch`, and then install `k2` and `lhotse`.
> 
> ```dockerfile
> RUN pip install torch==1.9.0 torchaudio==0.9.0 && \
>   \
>   pip install git+https://github.com/lhotse-speech/lhotse && \
>   \
>   git clone https://github.com/k2-fsa/k2.git /opt/k2 && \
>   cd /opt/k2 && \
>   python3 setup.py install && \
>   cd - && \
>   \
>   git clone https://github.com/k2-fsa/icefall && \
>   cd icefall && \
>   pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && \
>   cd - && \
>   \
>   rm ~/.cache/pip
> ```
> 
> I assume that you have installed CUDA and cuDNN correctly.
> 
> If you are not in China, you can remove `-i https://pypi.tuna.tsinghua.edu.cn/simple` from the dockerfile.

Actually, I am using the Dockerfile from icefall github repo ([here](https://github.com/k2-fsa/icefall/blob/master/docker/Ubuntu18.04-pytorch1.7.1-cuda11.0-cudnn8/Dockerfile)) and it is based on a pytorch image.

**Comment by mohsen-goodarzi** [comment]
> @mohsen-goodarzi Please pull the latest k2. It was just fixed in [k2-fsa/k2#958](https://github.com/k2-fsa/k2/pull/958)

@pzelasko 
I tried it with k2 v1.13 and latest Lhotse and k2 was imported correctly, but I still get the id mismatch error!

```
Traceback (most recent call last):
  File "./wav2vec2_conformer_ctc/train.py", line 787, in <module>
    main()
  File "./wav2vec2_conformer_ctc/train.py", line 778, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/workspace/gzi/wav2vec2_conformer_ctc/train.py", line 686, in run
    params=params,
  File "/workspace/gzi/wav2vec2_conformer_ctc/train.py", line 743, in scan_pessimistic_batches_for_oom
    batch = train_dl.dataset[cuts]
  File "/opt/conda/lib/python3.7/site-packages/lhotse/dataset/speech_recognition.py", line 99, in __getitem__
    validate_for_asr(cuts)
  File "/opt/conda/lib/python3.7/site-packages/lhotse/dataset/speech_recognition.py", line 202, in validate_for_asr
    validate(cuts)
  File "/opt/conda/lib/python3.7/site-packages/lhotse/qa.py", line 39, in validate
    validator(obj, read_data=read_data)
  File "/opt/conda/lib/python3.7/site-packages/lhotse/qa.py", line 480, in validate_cut_set
    validate_cut(c, read_data=read_data)
  File "/opt/conda/lib/python3.7/site-packages/lhotse/qa.py", line 389, in validate_cut
    f"MonoCut {c.id}: supervision {s.id} has a mismatched recording_id "
AssertionError: MonoCut 7357-94126-0014-26472-0_sp0.9: supervision 7357-94126-0014_sp0.9 has a mismatched recording_id (expected None, supervision has 7357-94126-0014_sp0.9)
```

**Comment by mohsen-goodarzi** [comment]
And this is the related cut:
`MonoCut(id='2893-139310-0027-4703-0_sp0.9', start=0, duration=18.25, channel=0, supervisions=[SupervisionSegment(id='2893-139310-0027_sp0.9', recording_id='2893-139310-0027_sp0.9', start=0.0, duration=18.25, channel=0, text='A WAVING INCESSANT CONFUSION OF CROWDED SHOUTING FACES MEN AND WOMEN TOGETHER WAVING PALE BLUE GARMENTS EXTENDED HANDS MANY WERE STANDING ONE MAN IN RAGS OF DARK BROWN A GAUNT FIGURE STOOD ON THE SEAT AND WAVED A BLACK CLOTH', language='English', speaker='2893', gender=None, custom=None, alignment=None)], features=Features(type='wav2vec2-feature-extractor', num_frames=913, num_features=512, frame_shift=0.02, sampling_rate=16000, start=0, duration=18.25, storage_type='numpy_hdf5', storage_path='data/wav2vec2_new/feats_train-clean-100.h5', storage_key='0ae4df4c-1eb3-49c2-864a-ba8abd633522', recording_id='None', channels=0), recording=None, custom=None)`

There is a `recording_id='None'`, but I have no idea why is it none!

**Comment by pzelasko** [comment]
It looks like you might have dropped it somewhere during data preparation earlier. If recording is not available, then `cut.recording_id` tries to look up `cut.features.recording_id`, but that one is set to string `'None'`. It seems the issue is somewhere in your data preparation and not in Lhotse in this case.

**Comment by pzelasko** [comment]
If you're 100% sure the data is sane otherwise, you can fix your data with a few lines of Python, doing sth like:

```python
with CutSet.open_writer("cuts_fixed.jsonl.gz") as w:
    for cut in load_manifest_lazy("cuts.jsonl.gz"):
        cut.features.recording_id = cut.supervisions[0].recording_id
        w.write(cut)
```

**Comment by mohsen-goodarzi** [comment]
> It looks like you might have dropped it somewhere during data preparation earlier. If recording is not available, then `cut.recording_id` tries to look up `cut.features.recording_id`, but that one is set to string `'None'`. It seems the issue is somewhere in your data preparation and not in Lhotse in this case.

While I was trying to figure out why recording is dropped, I came to this ([here](https://github.com/lhotse-speech/lhotse/blob/b3b96a1d64fa3bd97c9c9bf32ef0e8b4806b87ef/lhotse/cut.py#L4442)):

```
        :param mix_eagerly: Related to how the features are extracted for ``MixedCut``
            instances, if any are present.
            When False, extract and store the features for each track separately,
            and mix them dynamically when loading the features.
            When True, mix the audio first and store the mixed features,
            returning a new ``MonoCut`` instance with the same ID.
            The returned ``MonoCut`` will not have a ``Recording`` attached.
```

Could it be the reason?!

**Comment by pzelasko** [comment]
Ah, that makes sense. I’ll see how to better handle your use case there.

**Comment by pzelasko** [comment]
Please try this PR, unfortunately you will need to either re-generate your data, or manually overwrite recording_id in `cut.features` if re-computation is problematic.

**Comment by mohsen-goodarzi** [comment]
@pzelasko 
I already did the manual overwriting and now it is under training.
At earliest possible time, I will also try your fix.
Thank you so much.
